# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  branches:
    include:
      - develop

# azure-pipelines.yml
pool:
  vmImage: "macOS 10.14"
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.2.0"
    displayName: "Install Node"
  - script: npm install
    displayName: "Install dependencies"
  - script: npx jetify
    displayName: "Install jetify"
  - task: Gradle@2
    displayName: "Build APK"
    inputs:
      gradleWrapperFile: "android/gradlew"
      workingDirectory: "android/"
      options: "-PversionName=$(NEW_VERSION) -PversionCode=$(Build.BuildId)"
      tasks: "assembleRelease"
      publishJUnitResults: false
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.8"
      gradleOptions: "-Xmx3072m"
      sonarQubeRunAnalysis: false

  - task: PublishBuildArtifacts@1
    displayName: "Publish APK to artifacts"
    inputs:
      PathtoPublish: "android/app/build/outputs/apk/release"
      ArtifactName: "android"
      publishLocation: "Container"